# Generated by Django 4.1.1 on 2022-10-01 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App_MartinFuron', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='cumpleaños',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
